# Crie um programa que leia um número inteiro e de sua tabuada
t = int(input('Digite um número para ver sua tabuada: '))
print(' {} x  1 = {}\n {} x  2 = {}\n {} x  3 = {}\n {} x  4 = {}\n {} x  5 = {}\n {} x  6 = {} \n {} x  7 = {} \n {} x  8 = {} \n {} x  9 = {} \n {} x 10 = {}'.format(t,(t*1),t,(t*2),t,(t*3),t,(t*4),t,(t*5),t,(t*6),t,(t*7),t,(t*8),t,(t*9),t,(t*10)))
print('')
print('=' * 14)
v = int(input('Digite outro valor: '))
print('')
print('{} X {:2} = {:2}'.format(v, 1, v*1))
print('{} X {:2} = {:2}'.format(v, 2, v*2))
print('{} X {:2} = {:2}'.format(v, 3, v*3))
print('{} X {:2} = {:2}'.format(v, 4, v*4))
print('{} X {:2} = {:2}'.format(v, 5, v*5))
print('{} X {:2} = {:2}'.format(v, 6, v*6))
print('{} X {:2} = {:2}'.format(v, 7, v*7))
print('{} X {:2} = {:2}'.format(v, 8, v*8))
print('{} X {:2} = {:2}'.format(v, 9, v*9))
print('{} X {:2} = {:2}'.format(v, 10,v*10))
print('#=#=' * 14)